### ISSUE TITLE
More player stats

### ISSUE THREAD

**Issue by jtmille3** [jtmille3/Comp#15]
Include total wins, ties, and losses.  Maybe winning percentage?  Not sure how that is calculated with ties.  Give the break down by season.

**Comment by pip8786** [comment]
Separate playoff and regular season records separately too.

**Comment by JackOfManyTrades** [comment]
A friendly user provided a few queries which may be useful to this Issue.  I'm attaching those queries in a file but have not validated them.

[player_stat_views.txt](https://github.com/jtmille3/Comp/files/2669769/player_stat_views.txt)

**Comment by JackOfManyTrades** [comment]
It would be cool to display the max goals scored in a single game and max total goals scored in a single season.  I think in order to accomplish this, we will need to separate the alltime statistics for players and goal keepers and give them each their own links.  Essentially the alltime stats table would expand to include several new columns mentioned above.  The goalie table should get expanded with similar new columns that apply to keepers, although those have not yet been called out.  Just putting thoughts down before I forget.

**Comment by JackOfManyTrades** [comment]
I've been experimenting with this to see what we could do.  Pushed branch "playerstats" which has a new Player Statistics summary report.  It's not finished but it reports on lots of player stats and separates Overall, Season, and Playoff displays.  I'd like to write an analog which is more defensive stat oriented.  Anyway, looks like this:
![image](https://user-images.githubusercontent.com/45641698/51292712-c4b05980-19d9-11e9-8ba5-025c45117180.png)  

The intent would be for this to replace the All Time Statistics once a goalie/defensive oriented analog is made.  Measuring defensive stats is tricky.  Shutouts and Avg Goals Against per game is about all we have to go on, but it's really a team stat (a lot of goals are team goals by I digress).  Could do some data normalization to the best defensive ranking of all teams in a given season or in history.  Make that some number, like 100, and scale everyone elses value to whatever their ratio was to the best defensive team.  Probably over thinking this.

**Comment by pip8786** [comment]
@JackOfManyTrades I just realized that those stats are divided by Regular Season and Playoffs, very cool. At first I thought the numbers seemed off but didn't realize it was split up (was looking on my phone while in Florida). 

I like all of this, thanks for all the work!

**Comment by JackOfManyTrades** [comment]
I added the Trophies count (season+playoff), changed default (first click) sort order on applicable tables to descending, and I validated code works even with a season not having any games played.  I performed this work in the playerstats branch and pulled into master in pull request https://github.com/jtmille3/Comp/pull/36

I don't think there's anything left to do in this issue, and will close unless I hear otherwise in a few days.

Jack

**Comment by JackOfManyTrades** [comment]
Implemented a few days ago.
