### ISSUE TITLE
Clicking on name in roster should also show player history graph

### ISSUE THREAD

**Issue by jasonbosko** [jtmille3/Comp#23]
Would be nice to have the same graph that you get when searching for a name to also show up when you click on a name in the team roster.

**Comment by jtmille3** [comment]
I think that is plausible without too much effort.  I'll look into it.
Good suggestion.

On Mon, Mar 7, 2016 at 11:46 AM, jasonbosko <notifications@github.com>
wrote:

> Would be nice to have the same graph that you get when searching for a
> name to also show up when you click on a name in the team roster.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jtmille3/Comp/issues/23>.
>



-- 
Jeff Miller
jeffmiller@jeffmiller.name
919-607-6639

**Comment by JackOfManyTrades** [comment]
I'll take a crack at this.  I've got prototype code which does this, but it needs cleanup.  Having a little difficulty squaring away the closure scope of some of the javascript functions.

**Comment by pip8786** [comment]
At the same time I’d like that modal to be slightly bigger. We could use some responsive stuff to size it appropriately. However the changes you had made to the legend of the x-axis helped out with this issue. Would also be nice to see regular season and playoff wins on the graph. Let me know if I should open new issues for those.

**Comment by JackOfManyTrades** [comment]
For simplicity, let's keep this issue specific to binding clicking player name to loading the graph that the search feature does.  Issue #21 is a more general place for enhancing the player display.  In that issue you stated "it becomes even more summary of the players career".  I agree with the sentiment of that statement.  However, I'm thinking we need more than a simple graph.  Perhaps a combination of a tabular display of a players past teams and the team standing as well as individual player stats and when they occurred.  More like how the ultimate app does a player's page.  Basically, I think we need to put more thought into what data the player display should include and how to depict that.  Especially with 2 comp seasons each year, the x-axis grows quickly.  There's lots we can do here, but lets think it through before implementing a few odds/ends piecemeal.

**Comment by JackOfManyTrades** [comment]
I refactored the prototype code I mentioned earlier to tidy it up.  I took a look at changing the modal size too.  The modal is provided by bootstrap and they provide 3 sizes, small - medium (current) - and large.  I thought bootstrap was responsive by design but apparently not all plugins are.  The large size is about 900px wide, the small 300px, and medium about 600px.  There's no simple way of changing that behavior.  Within the modal, the svg graph is hard-coded, so we can size that to match.  Large looks good to me on desktop browser but bootstrap uses min-width: 992px so anything less than 992px, it won't render.  Large is 50% bigger than what we have now, so it's more than slightly bigger.  I'm pushing the code with the larger modal.  If you think it's too big, let me know and I'll dial it back to medium.
